services:
  db:
    image: postgres:13-alpine 
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      TZ: Asia/Taipei
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      TZ: Asia/Taipei
      PYTHONUNBUFFERED: 1  
    depends_on:
      db:
        condition: service_healthy 
    volumes:
      - .:/app
      - /app/__pycache__  
    deploy:  
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
    name: crawler_postgres_data  

networks:
  app-network:
    name: crawler_network  